
[[constraint]]
  branch = "master"
  name = "github.com/kylelemons/godebug"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"


[[constraint]]
  name = "github.com/jroimartin/gocui"
  version = "0.3.0"
